// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zauidyivrvsgfpxdsugg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphdWlkeWl2cnZzZ2ZweGRzdWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjU5MzMsImV4cCI6MjA2NTYwMTkzM30.dAFv5jdw3Vf6g1p8bOhvqD0tWRFGdJ6sfg6au-dN2q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);